using DALSA.SaperaLT.SapClassBasic;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Varocto.Cameras
{

    public enum ServerCategory
    {
        ServerAll,
        ServerAcq,
        ServerAcqDevice
    };
    public class SaperaCameraManager
    {

        /// <summary>
        ///  Camera config files are generated by Dalsa
        /// </summary>
        /// 
        string lsoConfigFile = "C:\\development\\Devices\\Dalsa\\Camera Files\\T_Spyder_2_Default_Default.ccf";
        string octConfigFile = "C:\\development\\Devices\\Dalsa\\Camera Files\\OctoplusV1.ccf";

        // TODO double-check to see if the frame grabber server is always Xtium-CL_MX4_1.
        string cameraLinkServer = "Xtium-CL_MX4_1";

        private string lsoServerName;
        private string octServerName;
        private string lsoCameraName;
        private string octCameraName;

        public OctoplusCamera octCamera;
        public OctoplusCamera lsoCamera;


        private ServerCategory m_ServerCategory;

        public SaperaCameraManager()
        {

            octCamera = new OctoplusCamera (cameraLinkServer, octConfigFile, 1);
            lsoCamera = new OctoplusCamera(cameraLinkServer, lsoConfigFile, 0);
        }

        public void Initialize()
        {
           octCamera.Initialize();
           lsoCamera.Initialize();

        }

        public bool CreateObjects()
        {
            return (octCamera.CreateObjects() && lsoCamera.CreateObjects());
            //return lsoCamera.CreateObjects();
        }
        //private void InitServers()
        //{


        public void OpenSerialConnections()
        {
            octCamera.OpenSerialConnection();
        }

    }
}
